force-app/ifsr/main/schema/objects/Interaction__c/Interaction__c.object-meta.xml
<CustomObject>
    <description>Interaction Log and Staging Object</description>
    <label>Interaction</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Interaction_Mapping__c.object
<CustomObject>
    <description>Used to map fields from source Object to target Object in the Interactions process.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>A checkbox to activate an Interaction Mapping record.</description>
        <inlineHelpText>If checked, the Interaction Mapping is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_Field_API_Name__c</fullName>
        <description>The Source Object field you would like to map to a Target Object field. The value in this field must be in API format and matches an existing field on the Source Object.</description>
        <inlineHelpText>The Source Object field you would like to map to a Target Object field. Ensure this is in API format and matches the existing field on the Source Object.</inlineHelpText>
        <label>Source Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Object_API_Name__c</fullName>
        <description>The API name of the Source Object to map to the Target Object. When adding new values, ensure that you use the API name of the object.</description>
        <inlineHelpText>Select the Source Object to map to the Target Object.</inlineHelpText>
        <label>Source Object API Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Interaction__c</fullName>
                    <default>true</default>
                    <label>Interaction__c</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Field_API_Name__c</fullName>
        <description>The field on the Target Object you would like to map an Interaction field value to. The value in this field must be in API format and match an existing field on the Target Object.</description>
        <inlineHelpText>The field on the Target Object you would like to map to. Ensure this is in API format and matches the existing field on the Target Object.</inlineHelpText>
        <label>Target Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Object_API_Name__c</fullName>
        <description>The API name of the Target Object to map Interaction data to. When adding new values, ensure that you use the API name of the object.</description>
        <inlineHelpText>Select the Target Object to map Source Object data to.</inlineHelpText>
        <label>Target Object API Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CampaignMember</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>hed__Affiliation__c</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Interaction__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Interaction Mapping</label>
    <nameField>
        <displayFormat>INTMap-{000000}</displayFormat>
        <label>Interaction Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interaction Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/ifsr/main/test/classes/INT_InteractionMapping_Test.cls
/**
* @author Accenture
* @date 11/22/19
*
* Unit Tests for INT_InteractionMapping.trigger
*/
@IsTest
private class INT_InteractionMapping_Test {
    /**
     * Tests validation creating a new Interaction_Mapping__c record with a source field that does not exist on Interaction__c.
     */
    @IsTest
    private static void testErrorCreatingInteractionMapping() {
        // Arrange
        Interaction_Mapping__c testInteractionMappingError = new Interaction_Mapping__c(
            Target_Object_API_Name__c = 'Lead',
            Source_Object_API_Name__c = 'Interaction__c',
            Source_Field_API_Name__c = 'Some_Field_That_Is_Wrong__c',
            Target_Field_API_Name__c = 'Mobile_Phone__c',
            Active__c = true
        );

        // Act
        Test.startTest();
        try {
            insert testInteractionMappingError;
        } catch (Exception e) {
            // Assert
            System.assert(e.getMessage().contains('Source Field API Name \'Some_Field_That_Is_Wrong__c\' does not exist on Interaction'),
                'The test should have failed to create the mapping as \'Some_Field_That_Is_Wrong__c\' does not exist on Interaction__c.');
        }
        Test.stopTest();
    }

    /**
     * Tests validation creating a new Interaction_Mapping__c record with a source field that does not exist on Interaction__c.
     */
    @IsTest
    private static void testErrorCreatingSObjectMapping() {
        // Arrange
        Interaction_Mapping__c testLeadMappingError = new Interaction_Mapping__c(
            Target_Object_API_Name__c = 'Interaction__c',
            Source_Object_API_Name__c = 'Lead',
            Source_Field_API_Name__c = 'Some_Field_That_Is_Wrong__c',
            Target_Field_API_Name__c = 'Mobile_Phone__c',
            Active__c = true
        );

        // Act
        Test.startTest();
        try {
            insert testLeadMappingError;
        } catch (Exception e) {
            // Assert
            System.assert(e.getMessage().contains('Source Field API Name \'Some_Field_That_Is_Wrong__c\' does not exist on Lead'),
                'The test should have failed to create the mapping as \'Some_Field_That_Is_Wrong__c\' does not exist on Lead.');
        }
        Test.stopTest();
    }
}